services:
  movie:
    build: ./movie/
    ports:
      - "3200:3200"
  schedule:
    build: ./schedule/
    ports:
      - "3202:3202"
  booking:
    build: ./booking/
    ports:
      - "3201:3201"
  user:
    build: ./user/
    ports:
      - "3203:3203"

